services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=changeMe1!
    ports:
      - "1433:1433"
